name: Test, build and publish Golang services
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          check-latest: true

      - name: Install requirements
        run: npm install

      - name: Transpile TypeScript
        run: npx tsc

      - name: Run unit tests
        run: npm run test

      - name: Publish to VPS
        if: github.event_name != 'pull_request'
        run: |
          # Trust SSH host keys
          mkdir -p ~/.ssh/
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          curl 'https://raw.githubusercontent.com/JenswBE/setup/main/server/files/po/rsyncd-public-keys.txt' >> ~/.ssh/known_hosts

          # Setup SSH key
          touch ssh_key
          chmod 600 ssh_key
          echo '${{ secrets.SSH_KEY }}' > ssh_key

          # Sync generated files
          rsync --verbose --archive --delete --rsh='ssh -p ${{ vars.SSH_PORT }} -i ssh_key' public/ ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:/
